In [1]:
import torch


In [2]:
x = torch.rand(2,3)
x

tensor([[0.2884, 0.0557, 0.0446],
        [0.7478, 0.9557, 0.7320]])

In [3]:
x = torch.randn(2,3)
x

tensor([[ 0.1052,  0.7436, -1.1487],
        [ 1.2830, -0.2032,  2.3231]])

In [4]:
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x =  torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
x.size()

torch.Size([2, 3])

In [7]:
x.shape

torch.Size([2, 3])

In [8]:
x = torch.tensor([6,2])
x

tensor([6, 2])

In [9]:
x.size()

torch.Size([2])

## 数据类型

In [10]:
x = torch.tensor([6,2],dtype=torch.float32)
print(x)

tensor([6., 2.])


In [11]:
x.type(torch.int64)

tensor([6, 2])

In [12]:
x

tensor([6., 2.])

In [13]:
x=torch.ones(2,3,dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

## 与ndarray数据类型的转换

In [14]:
import numpy as np
a = np.random.randn(2,3)
a

array([[ 1.3914801 , -0.48207366,  0.1213693 ],
       [ 0.72828164, -0.35833152,  0.45124184]])

In [15]:
x1 = torch.from_numpy(a)
x1

tensor([[ 1.3915, -0.4821,  0.1214],
        [ 0.7283, -0.3583,  0.4512]], dtype=torch.float64)

In [16]:
x1.numpy()

array([[ 1.3914801 , -0.48207366,  0.1213693 ],
       [ 0.72828164, -0.35833152,  0.45124184]])

## 张量运算

In [17]:
x + x1

tensor([[2.3915, 0.5179, 1.1214],
        [1.7283, 0.6417, 1.4512]], dtype=torch.float64)

In [18]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
x + 3

tensor([[4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)

In [20]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
x1

tensor([[ 1.3915, -0.4821,  0.1214],
        [ 0.7283, -0.3583,  0.4512]], dtype=torch.float64)

In [22]:
x.add(x1)

tensor([[2.3915, 0.5179, 1.1214],
        [1.7283, 0.6417, 1.4512]], dtype=torch.float64)

In [23]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [24]:
x.add_(x1)

tensor([[2.3915, 0.5179, 1.1214],
        [1.7283, 0.6417, 1.4512]], dtype=torch.float64)

In [25]:
x

tensor([[2.3915, 0.5179, 1.1214],
        [1.7283, 0.6417, 1.4512]], dtype=torch.float64)

In [27]:
x.view(3,2)

tensor([[2.3915, 0.5179],
        [1.1214, 1.7283],
        [0.6417, 1.4512]], dtype=torch.float64)

In [28]:
x.view(-1,1)

tensor([[2.3915],
        [0.5179],
        [1.1214],
        [1.7283],
        [0.6417],
        [1.4512]], dtype=torch.float64)

In [29]:
x = x.mean()

In [30]:
x

tensor(1.3087, dtype=torch.float64)

In [31]:
x.item()

1.3086612835492295

## 张量的自动微分
将Torch.Tensor属性.requires_grad 设置成True，pytorch 将开始跟踪对此张量的所有操作。
完成计算后，可以调用.backward()并自动计算所有梯度。
钙张量的梯度将累加到.grad 属性中

In [32]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [33]:
x.requires_grad

True

In [34]:
x.grad

In [35]:
x.grad_fn  # 指向运算生成此张量的方法

In [37]:
# 运行张量运算
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [38]:
y.grad_fn

In [39]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


## 计算梯度

In [40]:
out.backward()  # 自动微分运算, 注意 out 是标量

# 打印梯度d（out）/dx
out = f(x)

In [41]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [43]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [44]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [48]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


也可使用.detach()来获得具有相同内容但不需要跟踪运算的新Tensor：

In [49]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [50]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [51]:
x.detach()

tensor([[1., 1.],
        [1., 1.]])

In [52]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

False


In [53]:
a.requires_grad_(True)
print(a.requires_grad)

True
