In [132]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import pandas as pd

In [133]:
data = pd.read_csv("./dataset/credit-a.csv")
data.head(5)

0  30.83    0.1  0.2  0.3  9  0.4  1.25  0.5  0.6  1  1.1  0.7  202    0.8  \
0  1  58.67  4.460    0    0  8    1  3.04    0    0  6    1    0   43  560.0   
1  1  24.50  0.500    0    0  8    1  1.50    0    1  0    1    0  280  824.0   
2  0  27.83  1.540    0    0  9    0  3.75    0    0  5    0    0  100    3.0   
3  0  20.17  5.625    0    0  9    0  1.71    0    1  0    1    2  120    0.0   
4  0  32.08  4.000    0    0  6    0  2.50    0    1  0    0    0  360    0.0   

   -1  
0  -1  
1  -1  
2  -1  
3  -1  
4  -1

In [154]:
data = pd.read_csv("./dataset/credit-a.csv",header=None)
data.head(5)

0      1      2   3   4   5   6     7   8   9   10  11  12   13     14  15
0   0  30.83  0.000   0   0   9   0  1.25   0   0   1   1   0  202    0.0  -1
1   1  58.67  4.460   0   0   8   1  3.04   0   0   6   1   0   43  560.0  -1
2   1  24.50  0.500   0   0   8   1  1.50   0   1   0   1   0  280  824.0  -1
3   0  27.83  1.540   0   0   9   0  3.75   0   0   5   0   0  100    3.0  -1
4   0  20.17  5.625   0   0   9   0  1.71   0   1   0   1   2  120    0.0  -1

In [135]:
# 拆分数据X和y
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]


In [136]:
X

0  30.83     0.1  0.2  0.3   9  0.4  1.25  0.5  0.6  1  1.1  0.7  202  \
0    1  58.67   4.460    0    0   8    1  3.04    0    0  6    1    0   43   
1    1  24.50   0.500    0    0   8    1  1.50    0    1  0    1    0  280   
2    0  27.83   1.540    0    0   9    0  3.75    0    0  5    0    0  100   
3    0  20.17   5.625    0    0   9    0  1.71    0    1  0    1    2  120   
4    0  32.08   4.000    0    0   6    0  2.50    0    1  0    0    0  360   
..  ..    ...     ...  ...  ...  ..  ...   ...  ...  ... ..  ...  ...  ...   
647  0  21.08  10.085    1    1  11    1  1.25    1    1  0    1    0  260   
648  1  22.67   0.750    0    0   0    0  2.00    1    0  2    0    0  200   
649  1  25.25  13.500    1    1  13    7  2.00    1    0  1    0    0  200   
650  0  17.92   0.205    0    0  12    0  0.04    1    1  0    1    0  280   
651  0  35.00   3.375    0    0   0    1  8.29    1    1  0    0    0    0   

       0.8  
0    560.0  
1    824.0  
2      3.0  
3      0.0  
4      0.0  
..     ...  
647    0.0  
648  394.0  
649    1.0  
650  750.0  
651    0.0  

[652 rows x 15 columns]

In [137]:
Y

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
647    1
648    1
649    1
650    1
651    1
Name: -1, Length: 652, dtype: int64

In [138]:
# 把-1 替换成0
Y = data.iloc[:,-1].replace(-1, 0)
Y

0      0
1      0
2      0
3      0
4      0
      ..
647    1
648    1
649    1
650    1
651    1
Name: -1, Length: 652, dtype: int64

In [139]:
Y.value_counts()

1    357
0    295
Name: -1, dtype: int64

In [140]:
X = torch.from_numpy(X.values).type(torch.FloatTensor)

In [141]:
X=X.type(torch.FloatTensor)
X

tensor([[1.0000e+00, 5.8670e+01, 4.4600e+00,  ..., 0.0000e+00, 4.3000e+01,
         5.6000e+02],
        [1.0000e+00, 2.4500e+01, 5.0000e-01,  ..., 0.0000e+00, 2.8000e+02,
         8.2400e+02],
        [0.0000e+00, 2.7830e+01, 1.5400e+00,  ..., 0.0000e+00, 1.0000e+02,
         3.0000e+00],
        ...,
        [1.0000e+00, 2.5250e+01, 1.3500e+01,  ..., 0.0000e+00, 2.0000e+02,
         1.0000e+00],
        [0.0000e+00, 1.7920e+01, 2.0500e-01,  ..., 0.0000e+00, 2.8000e+02,
         7.5000e+02],
        [0.0000e+00, 3.5000e+01, 3.3750e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])

In [142]:
Y = torch.from_numpy(Y.values.reshape(-1, 1)).type(torch.FloatTensor)
Y

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
      

In [143]:
# 因为是二分类问题，所以最终需要将线性计算结果，拟合到0，1之间，用sigmoid函数，因为15个特征，所以选择15，输出的是0，1之间的概率，就是1个特征

In [144]:
model = nn.Sequential(
    nn.Linear(15,1),
    nn.Sigmoid()
    )

In [145]:
model

Sequential(
  (0): Linear(in_features=15, out_features=1, bias=True)
  (1): Sigmoid()
)

In [146]:
# 二元交叉熵, 二分类 
loss_fn = nn.BCELoss()


In [147]:
# 目标函数,设置目标函数的优化策略
opt = torch.optim.Adam(model.parameters(), lr=0.0001)
opt

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.0001
    maximize: False
    weight_decay: 0
)

In [148]:
batches = 16
# 整除的方式, 不足一个batch的就舍掉,比如0.25
no_of_batches = len(Y)//16

In [149]:
for epoch in range(1000):
    total_loss = 0
    for batch in range(no_of_batches):
        # 起始位置
        start = batch*batches
        end = start + batches
        # start = batch*batches
        # end = start + batches
        x = X[start: end]
        y = Y[start: end]
        # 计算loss
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        total_loss+=loss.item()
        opt.zero_grad()
        loss.backward()
        opt.step()
        # 实际预测结果
    print(epoch,"acc",((model(X).data.numpy() > 0.5).astype('int')==Y.numpy()).mean())
    print(epoch,"loss",total_loss)

0 acc 0.35276073619631904
0 loss 1182.7810492515564
1 acc 0.35736196319018404
1 loss 1171.3425784111023
2 acc 0.3588957055214724
2 loss 1159.9889831542969
3 acc 0.3604294478527607
3 loss 1148.8308384418488
4 acc 0.3665644171779141
4 loss 1137.91441822052
5 acc 0.36809815950920244
5 loss 1137.6787827014923
6 acc 0.37116564417177916
6 loss 1132.300015449524
7 acc 0.37116564417177916
7 loss 1121.9657998085022
8 acc 0.37423312883435583
8 loss 1117.3062319755554
9 acc 0.38190184049079756
9 loss 1107.7318037748337
10 acc 0.38496932515337423
10 loss 1098.3357602357864
11 acc 0.38650306748466257
11 loss 1089.409782409668
12 acc 0.39723926380368096
12 loss 1081.1678120493889
13 acc 0.4049079754601227
13 loss 1073.8457543849945
14 acc 0.4217791411042945
14 loss 1067.7646329402924
15 acc 0.4386503067484663
15 loss 1073.733492553234
16 acc 0.450920245398773
16 loss 1070.5249483585358
17 acc 0.4647239263803681
17 loss 1068.3022458553314
18 acc 0.48006134969325154
18 loss 1066.7793003618717
19 acc 0

In [150]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-1.0363e-01, -7.4631e-03, -5.6751e-03,  3.8822e-01,  2.1284e-02,
                       -1.4004e-02,  1.8759e-01, -1.7392e-01,  1.8903e+00,  4.6770e-01,
                       -1.7017e-01, -7.3336e-02,  2.6795e-02,  1.0146e-03, -3.4693e-04]])),
             ('0.bias', tensor([0.0062]))])

In [153]:
# 实际预测结果
((model(X).data.numpy() > 0.5).astype('int')==Y.numpy()).mean()

0.8680981595092024