In [103]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F
%matplotlib inline

In [104]:
data = pd.read_csv("dataset/HR.csv")
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   part  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   part                   14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [106]:
# 返回某一列的唯一值
data.part.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [107]:
data.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [108]:
data.groupby(["salary","part"]).size()

salary  part       
high    IT               83
        RandD            51
        accounting       74
        hr               45
        management      225
        marketing        80
        product_mng      68
        sales           269
        support         141
        technical       201
low     IT              609
        RandD           364
        accounting      358
        hr              335
        management      180
        marketing       402
        product_mng     451
        sales          2099
        support        1146
        technical      1372
medium  IT              535
        RandD           372
        accounting      335
        hr              359
        management      225
        marketing       376
        product_mng     383
        sales          1772
        support         942
        technical      1147
dtype: int64

In [109]:
pd.get_dummies(data.salary)

high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [110]:
data = data.join(pd.get_dummies(data.salary))

In [111]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   part                   14999 non-null  object 
 9   salary                 14999 non-null  object 
 10  high                   14999 non-null  uint8  
 11  low                    14999 non-null  uint8  
 12  medium                 14999 non-null  uint8  
dtypes: float64(2), int64(6), object(2), uint8(3)
memory usage: 1.2+ MB


In [112]:
del data["salary"]

In [113]:
data = data.join(pd.get_dummies(data.part))
del data["part"]

In [114]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  high  low  \
0                   3              0     1                      0     0    1   
1                   6              0     1                      0     0    0   
2                   4              0     1                      0     0    0   
3                   5              0     1                      0     0    1   
4                   3              0     1                      0     0    1   

   ...  IT  RandD  accounting  hr  management  marketing  product_mng  sales  \
0  ...   0      0           0   0           0          0            0      1   
1  ...   0      0           0   0           0          0            0      1   
2  ...   0      0           0   0           0          0            0      1   
3  ...   0      0           0   0           0          0            0      1   
4  ...   0      0           0   0           0          0            0      1   

   support  technical  
0        0          0  
1        0          0  
2        0          0  
3        0          0  
4        0          0  

[5 rows x 21 columns]

In [115]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   high                   14999 non-null  uint8  
 9   low                    14999 non-null  uint8  
 10  medium                 14999 non-null  uint8  
 11  IT                     14999 non-null  uint8  
 12  RandD                  14999 non-null  uint8  
 13  accounting             14999 non-null  uint8  
 14  hr                     14999 non-null  uint8  
 15  ma

In [116]:
data.left.value_counts()

0    11428
1     3571
Name: left, dtype: int64

全部预测为不离职,还有76%的正确率，所以，若是不能超过它，则没意义

In [117]:
11428/len(data)

0.7619174611640777

In [118]:
Y_data = data.left.values.reshape(-1,1)


In [119]:
Y_data.shape

(14999, 1)

In [120]:
Y = torch.from_numpy(Y_data).type(torch.float32)

In [121]:
Y

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]])

In [122]:
X_data = data[[c for c in data.columns if c!="left"]].values
X_data

array([[0.38, 0.53, 2.  , ..., 1.  , 0.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 1.  , 0.  , 0.  ],
       [0.11, 0.88, 7.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [123]:
X = torch.from_numpy(X_data).type(torch.float32)

In [124]:
X

tensor([[0.3800, 0.5300, 2.0000,  ..., 1.0000, 0.0000, 0.0000],
        [0.8000, 0.8600, 5.0000,  ..., 1.0000, 0.0000, 0.0000],
        [0.1100, 0.8800, 7.0000,  ..., 1.0000, 0.0000, 0.0000],
        ...,
        [0.3700, 0.5300, 2.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.1100, 0.9600, 6.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.3700, 0.5200, 2.0000,  ..., 0.0000, 1.0000, 0.0000]])

## 创建模型

In [125]:
from torch import nn

nn.Module:继承这个类
__init__:初始化所有层
forward: 定义模型的运算过程（前向传播过程）

In [126]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.liner_1 = nn.Linear(20, 64)
        self.liner_2 = nn.Linear(64, 64)
        self.liner_3 = nn.Linear(64,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, input):
        x = self.liner_1(input)
        x = F.relu(x)
        x = self.liner_2(x)
        x = F.relu(x)
        x = self.liner_3(x)
        x = self.sigmoid(x)
        return x

        

In [127]:
model = Model()
model

Model(
  (liner_1): Linear(in_features=20, out_features=64, bias=True)
  (liner_2): Linear(in_features=64, out_features=64, bias=True)
  (liner_3): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [128]:
lr = 0.0001


In [129]:
def get_model():
    model = Model()
    opt = torch.optim.Adam(model.parameters(),lr=lr)
    return model, opt

In [130]:
model, optim = get_model()

## 定义损失函数

In [131]:
loss_fn = nn.BCELoss()

In [132]:
batch = 64
no_of_batches = len(data)//batch
epochs = 100

In [133]:
for epoch in range(epochs):
    for i in range(no_of_batches):
        start = i * batch
        end = start + batch
        x = X[start: end]
        y = Y[start: end]
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        # 将model.parameters()
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print("epoch:",epoch,"loss:",loss_fn(model(X),Y).data.item())

        

epoch: 0 loss: 0.7176766991615295
epoch: 1 loss: 0.7330382466316223
epoch: 2 loss: 0.7248596549034119
epoch: 3 loss: 0.7130147218704224
epoch: 4 loss: 0.7042692303657532
epoch: 5 loss: 0.6954006552696228
epoch: 6 loss: 0.6861502528190613
epoch: 7 loss: 0.6766253709793091
epoch: 8 loss: 0.6662309169769287
epoch: 9 loss: 0.6568509340286255
epoch: 10 loss: 0.6510912179946899
epoch: 11 loss: 0.6379894614219666
epoch: 12 loss: 0.6282041072845459
epoch: 13 loss: 0.6187160611152649
epoch: 14 loss: 0.6065700650215149
epoch: 15 loss: 0.6029775738716125
epoch: 16 loss: 0.5957040190696716
epoch: 17 loss: 0.5890514850616455
epoch: 18 loss: 0.5840762853622437
epoch: 19 loss: 0.5795418620109558
epoch: 20 loss: 0.5755941271781921
epoch: 21 loss: 0.5718924403190613
epoch: 22 loss: 0.5686972737312317
epoch: 23 loss: 0.5657935738563538
epoch: 24 loss: 0.5636541843414307
epoch: 25 loss: 0.5606536269187927
epoch: 26 loss: 0.5726396441459656
epoch: 27 loss: 0.565210223197937
epoch: 28 loss: 0.5638801455497

In [134]:
loss_fn(model(X),Y)

tensor(0.5163, grad_fn=<BinaryCrossEntropyBackward0>)

In [135]:
from torch.utils.data import TensorDataset

In [136]:
HRdataset = TensorDataset(X,Y)


In [137]:
HRdataset

In [138]:
len(HRdataset)

14999

In [139]:
HRdataset[0]

(tensor([  0.3800,   0.5300,   2.0000, 157.0000,   3.0000,   0.0000,   0.0000,
           0.0000,   1.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   1.0000,   0.0000,   0.0000]),
 tensor([1.]))

In [140]:
HRdataset[2:5]

(tensor([[1.1000e-01, 8.8000e-01, 7.0000e+00, 2.7200e+02, 4.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00],
         [7.2000e-01, 8.7000e-01, 5.0000e+00, 2.2300e+02, 5.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00],
         [3.7000e-01, 5.2000e-01, 2.0000e+00, 1.5900e+02, 3.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [141]:
for epoch in range(epochs):
    for i in range(no_of_batches):
        # 这里有一个不好的事儿，是带顺序的。
        x,y = HRdataset[i*batch:i*batch+batch]
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        # 将model.parameters()
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print("epoch:",epoch,"loss:",loss_fn(model(X),Y).data.item())


epoch: 0 loss: 0.5136058926582336
epoch: 1 loss: 0.5114843845367432
epoch: 2 loss: 0.510262131690979
epoch: 3 loss: 0.5087526440620422
epoch: 4 loss: 0.507613480091095
epoch: 5 loss: 0.506384015083313
epoch: 6 loss: 0.5054643750190735
epoch: 7 loss: 0.5044152736663818
epoch: 8 loss: 0.5036347508430481
epoch: 9 loss: 0.5024536848068237
epoch: 10 loss: 0.5015662908554077
epoch: 11 loss: 0.5005391836166382
epoch: 12 loss: 0.49973949790000916
epoch: 13 loss: 0.49867355823516846
epoch: 14 loss: 0.5046321153640747
epoch: 15 loss: 0.5001006126403809
epoch: 16 loss: 0.4966948926448822
epoch: 17 loss: 0.4941505789756775
epoch: 18 loss: 0.49148029088974
epoch: 19 loss: 0.4907250702381134
epoch: 20 loss: 0.48895642161369324
epoch: 21 loss: 0.4876853823661804
epoch: 22 loss: 0.48684147000312805
epoch: 23 loss: 0.4855191707611084
epoch: 24 loss: 0.4845154583454132
epoch: 25 loss: 0.48337802290916443
epoch: 26 loss: 0.4827190041542053
epoch: 27 loss: 0.48085927963256836
epoch: 28 loss: 0.47980985045

## dataloader类 
上面的已经够好了，可是解决不了顺序固定的问题，dataloader可以解决，不需要自己切片

In [142]:
from torch.utils.data import DataLoader

In [143]:
HR_ds = TensorDataset(X,Y)
HR_dl = DataLoader(HR_ds,batch_size=batch,shuffle=True)

In [144]:
for epoch in range(epochs):
    for x,y in HR_dl:
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print("epoch:",epoch,"loss:",loss_fn(model(X),Y).data.item())


epoch: 0 loss: 0.35637837648391724
epoch: 1 loss: 0.345561683177948
epoch: 2 loss: 0.3360661566257477
epoch: 3 loss: 0.32839760184288025
epoch: 4 loss: 0.32060086727142334
epoch: 5 loss: 0.31408563256263733
epoch: 6 loss: 0.3048373758792877
epoch: 7 loss: 0.2976686358451843
epoch: 8 loss: 0.28967583179473877
epoch: 9 loss: 0.2826271653175354
epoch: 10 loss: 0.2768506109714508
epoch: 11 loss: 0.26995277404785156
epoch: 12 loss: 0.26449429988861084
epoch: 13 loss: 0.25879815220832825
epoch: 14 loss: 0.25391989946365356
epoch: 15 loss: 0.25462186336517334
epoch: 16 loss: 0.2455013543367386
epoch: 17 loss: 0.2424476444721222
epoch: 18 loss: 0.238833948969841
epoch: 19 loss: 0.23658283054828644
epoch: 20 loss: 0.23212184011936188
epoch: 21 loss: 0.23242434859275818
epoch: 22 loss: 0.2308107614517212
epoch: 23 loss: 0.22689057886600494
epoch: 24 loss: 0.2232292741537094
epoch: 25 loss: 0.22141742706298828
epoch: 26 loss: 0.22000618278980255
epoch: 27 loss: 0.2183222472667694
epoch: 28 loss: 

## 以上代码已经很好了
但是仍然有两个缺点：
1.不能打印训练过程中的正确率，对应loss的变化 所以要计算模型正确率的问题
2.解决过拟合，欠拟合的问题， 可能在train set 上好，但是在test set 上可能会很垃圾，所以要划分train， test

In [145]:
from sklearn.model_selection import train_test_split
train_x,test_x, train_y, test_y = train_test_split(X_data, Y_data,test_size=0.25)

In [146]:
type(train_x)

numpy.ndarray

In [147]:
train_x = torch.from_numpy(train_x).type(torch.float32)
train_y = torch.from_numpy(train_y).type(torch.float32)
test_x = torch.from_numpy(test_x).type(torch.float32)
test_y = torch.from_numpy(test_y).type(torch.float32)


In [148]:
train_ds = TensorDataset(train_x,train_y)
train_dl = DataLoader(train_ds,batch_size=batch,shuffle=True)

In [149]:
test_ds = TensorDataset(test_x,test_y)
# 没有必要shuffle， 可以加 但是没有意义
test_dl = DataLoader(test_ds,batch_size=batch)

 ## 如何计算正确率

In [150]:
(y_pred>0.5).type(torch.int32)

tensor([[1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0]], dtype=torch.int32)

(y_pred==labels).float().mean()

In [154]:
def accuracy(y_pred, y_true):
    y_pred = (y_pred>0.5).float()
    acc = (y_pred==y_true).float().mean()
    return acc
    


In [156]:
for epoch in range(epochs):
    for x,y in train_dl:
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        train_pred_y = model(train_x)
        epoch_train_accuracy = accuracy(train_pred_y,train_y)
        print("epoch:",epoch,"loss:",loss_fn(train_pred_y,train_y).data.item(),"accuracy:",epoch_train_accuracy.item())

        test_pred_y = model(test_x)
        epoch_test_accuracy = accuracy(test_pred_y,test_y)
        print("epoch:",epoch,"loss:",loss_fn(test_pred_y,test_y).data.item(),"accuracy:",epoch_test_accuracy.item())

epoch: 0 loss: 0.13660049438476562 accuracy: 0.9531514048576355
epoch: 0 loss: 0.14784054458141327 accuracy: 0.9480000138282776
epoch: 1 loss: 0.13425779342651367 accuracy: 0.956885039806366
epoch: 1 loss: 0.14125746488571167 accuracy: 0.9541333317756653
epoch: 2 loss: 0.13615725934505463 accuracy: 0.9599075317382812
epoch: 2 loss: 0.14484205842018127 accuracy: 0.9549333453178406
epoch: 3 loss: 0.1343972533941269 accuracy: 0.9571517705917358
epoch: 3 loss: 0.14539027214050293 accuracy: 0.9522666931152344
epoch: 4 loss: 0.13422666490077972 accuracy: 0.9564405679702759
epoch: 4 loss: 0.14525920152664185 accuracy: 0.9485333561897278
epoch: 5 loss: 0.13511523604393005 accuracy: 0.9531514048576355
epoch: 5 loss: 0.14574949443340302 accuracy: 0.9482666850090027
epoch: 6 loss: 0.13374224305152893 accuracy: 0.9605298042297363
epoch: 6 loss: 0.14212313294410706 accuracy: 0.9562666416168213
epoch: 7 loss: 0.13201026618480682 accuracy: 0.9604409337043762
epoch: 7 loss: 0.14138095080852509 accurac