In [3]:
import torch
x = torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.empty(5,3)

tensor([[0.0000e+00, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 2.1845e-29, 8.4078e-43],
        [2.0027e-19, 7.8026e+34, 0.0000e+00],
        [0.0000e+00, 2.1019e-44, 0.0000e+00],
        [2.1846e-29, 8.4078e-43, 4.4377e+27]])

In [7]:
torch.rand(5,3)

tensor([[0.2173, 0.7196, 0.3444],
        [0.4581, 0.8445, 0.8194],
        [0.0971, 0.5132, 0.4266],
        [0.8426, 0.1225, 0.6529],
        [0.9829, 0.9094, 0.0874]])

In [9]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = torch.tensor([2.5,3.5])
x

tensor([2.5000, 3.5000])

In [11]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [12]:
torch.randn_like(x,dtype=torch.float)

tensor([[-0.7416,  0.4444,  0.1054],
        [ 0.6074, -0.7169, -0.6716],
        [-0.9817, -0.1346,  0.1183],
        [-0.4002,  0.2464,  0.9182],
        [ 1.3303,  2.1349,  0.7589]])

In [13]:
x.size()

torch.Size([5, 3])

In [15]:
y  = torch.rand(5,3)
y

tensor([[0.8179, 0.1370, 0.1067],
        [0.1339, 0.2415, 0.7505],
        [0.9376, 0.8129, 0.1004],
        [0.0435, 0.8124, 0.6438],
        [0.1909, 0.3793, 0.6158]])

In [16]:
torch.add(x,y)

tensor([[1.8179, 1.1370, 1.1067],
        [1.1339, 1.2415, 1.7505],
        [1.9376, 1.8129, 1.1004],
        [1.0435, 1.8124, 1.6438],
        [1.1909, 1.3793, 1.6158]], dtype=torch.float64)

In [19]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[1.8179, 1.1370, 1.1067],
        [1.1339, 1.2415, 1.7505],
        [1.9376, 1.8129, 1.1004],
        [1.0435, 1.8124, 1.6438],
        [1.1909, 1.3793, 1.6158]])

In [20]:
y.add_(x)
y

tensor([[1.8179, 1.1370, 1.1067],
        [1.1339, 1.2415, 1.7505],
        [1.9376, 1.8129, 1.1004],
        [1.0435, 1.8124, 1.6438],
        [1.1909, 1.3793, 1.6158]])

In [21]:
x.copy_(y)

tensor([[1.8179, 1.1370, 1.1067],
        [1.1339, 1.2415, 1.7505],
        [1.9376, 1.8129, 1.1004],
        [1.0435, 1.8124, 1.6438],
        [1.1909, 1.3793, 1.6158]], dtype=torch.float64)

In [22]:
x.add_(y)

tensor([[3.6358, 2.2741, 2.2134],
        [2.2679, 2.4830, 3.5011],
        [3.8752, 3.6259, 2.2008],
        [2.0870, 3.6247, 3.2875],
        [2.3819, 2.7585, 3.2317]], dtype=torch.float64)

In [23]:
x[:,1]

tensor([2.2741, 2.4830, 3.6259, 3.6247, 2.7585], dtype=torch.float64)

In [24]:
x = torch.randn(4,4)
x

tensor([[-0.3809,  0.9532,  0.3862, -2.9088],
        [-0.6540,  0.1099, -0.4441, -1.5041],
        [ 0.4603, -0.3393, -0.8480, -0.2956],
        [-0.0557,  0.2557, -0.1371,  1.0411]])

In [25]:
y  = x.view(16)
y

tensor([-0.3809,  0.9532,  0.3862, -2.9088, -0.6540,  0.1099, -0.4441, -1.5041,
         0.4603, -0.3393, -0.8480, -0.2956, -0.0557,  0.2557, -0.1371,  1.0411])

In [26]:
z = x.view(-1,8)
z

tensor([[-0.3809,  0.9532,  0.3862, -2.9088, -0.6540,  0.1099, -0.4441, -1.5041],
        [ 0.4603, -0.3393, -0.8480, -0.2956, -0.0557,  0.2557, -0.1371,  1.0411]])

In [27]:
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
x = torch.randn(1)
x

tensor([-1.2471])

In [29]:
x.item()

-1.2471071481704712

In [30]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [31]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [32]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [33]:
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [34]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [35]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [36]:
np.add(a,1,out=a)


array([2., 2., 2., 2., 2.])

In [37]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [39]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu"),torch.double)

tensor([-0.2471], device='cuda:0')
tensor([-0.2471]) torch.float64


In [40]:
x1 = torch.ones(3,3)
x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
x = torch.ones(2,2,requires_grad = True)
x


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [42]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [43]:
x.grad_fn

In [44]:
y.grad_fn

In [45]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [46]:
a = torch.randn(2,2)
a = ((a * 3)/ (a - 1))
print(a.requires_grad)

False


In [47]:
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

True


In [48]:
out.backward()

In [49]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])